# -*- coding: utf-8 -*-
"""Gaficas python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9qkZqD14m2ntKX9mtKZCumoVL0ipHKX
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter

# Subir archivo
uploaded = files.upload()

# Leer CSV
df = pd.read_csv("CNST_Dataset.csv")

# Convertir a fecha
df["datetime"] = pd.to_datetime(df["datetime"])
df["date"] = df["datetime"].dt.date

# Agrupar por día y calcular velocidad promedio
speed_by_day = df.groupby("date")["speed"].mean().dropna()

# Graficar
plt.figure(figsize=(12,6))
speed_by_day.head(15).plot(kind="bar", color="orange")

plt.title("Velocidad promedio por día (primeros 15 días con datos)")
plt.xlabel("Fecha")
plt.ylabel("Velocidad promedio")

# Mostrar siempre con 2 decimales
plt.gca().yaxis.set_major_formatter(FormatStrFormatter('%.2f'))

plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""# Segundo grafico"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# Subir archivo
uploaded = files.upload()

# Leer dataset
df = pd.read_csv("ds_salaries.csv")

# Agrupar niveles de experiencia
exp_counts = df["experience_level"].value_counts()

# Graficar
plt.figure(figsize=(7,7))
plt.pie(exp_counts, labels=exp_counts.index, autopct='%1.1f%%', startangle=140)

plt.title("Distribución por nivel de experiencia")
plt.show()

"""# Tercer grafico"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar el CSV
df = pd.read_csv("prog_book.csv")

# --- 3. Top 10 libros con más Reviews ---
# Reviews viene como object, hay que pasarlo a numérico
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

top_reviews = df.nlargest(10, "Reviews")[["Book_title", "Reviews"]]

plt.figure(figsize=(10,6))
plt.barh(top_reviews["Book_title"], top_reviews["Reviews"])
plt.title("Top 10 libros con más Reviews")
plt.xlabel("Cantidad de Reviews")
plt.ylabel("Título del libro")
plt.gca().invert_yaxis()  # para que el más grande quede arriba
plt.show()